[dependencies]
raw-window-handle = "0.6"

[dev-dependencies]
tao = { version = "0.31" }
winit = { version = "0.30" }

[lib]
path = "Source/lib.rs"

[package]
authors = ["Tauri Programme within The Commons Conservancy"]
categories = ["gui"]
description = "Make your windows vibrant."
documentation = "https://docs.rs/tauri-plugin-vibrancy"
edition = "2024"
keywords = ["vibrancy", "acrylic", "mica", "blur", "windowing"]
license-file = "LICENSE"
name = "window-vibrancy"
readme = "README.md"
repository = "https://github.com/tauri-apps/tauri-plugin-vibrancy"
rust-version = "1.85.0"
version = "0.5.2"

[package.metadata]

[package.metadata.docs]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-apple-darwin", "x86_64-pc-windows-msvc"]

[target]

[target.'cfg(target_os = "macos")']

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.0"
objc2-app-kit = { version = "0.3.0", default-features = false, features = [
  "std",
  "NSApplication",
  "NSGraphics",
  "NSResponder",
  "NSView",
  "NSVisualEffectView",
] }
objc2-foundation = { version = "0.3.0", default-features = false, features = [
  "std",
  "NSThread",
  "NSGeometry",
] }

[target.'cfg(target_os = "windows")']

[target.'cfg(target_os = "windows")'.dependencies]
windows-version = "0.1"

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
features = [
	"Win32_Foundation",
	"Win32_System_LibraryLoader",
	"Win32_System_SystemInformation",
	"Win32_Graphics_Gdi",
	"Win32_Graphics_Dwm",
	"Win32_UI_WindowsAndMessaging",
]
version = "0.59.0"
